language: ruby

branches:
  only:
    - master
    - staging

bundler_args: --without mysql development

notifications:
  email:
    - common-effort@pivotallabs.com
  webhooks:
    urls:
    - http://projectmonitor-staging.pivotallabs.com/projects/d30b8651-bd0f-40ac-87c2-0fd662363e91/status
    - http://requestb.in/1ays2c01
    on_start: true
rvm:
  - 2.0.0

cache:
  bundler: true

before_script:
  - "sudo apt-get install memcached"
  - "bundle exec rake travis:setup"
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"

script: "bundle exec rake travis"
